//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYB.DeviceManagementSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeviceMgmtEntities : DbContext
    {
        public DeviceMgmtEntities()
            : base("name=DeviceMgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<Manufacturer> Manufacturer { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<Device> Device { get; set; }
        public DbSet<DeviceType> DeviceType { get; set; }
        public DbSet<MaintainRecord> MaintainRecord { get; set; }
        public DbSet<Permision> Permision { get; set; }
        public DbSet<RepairRecord> RepairRecord { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Project> Project { get; set; }
    }
}
